# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            A Verseless Book of Mormon
tagline:          
url:              http://honestcoyote.github.io
paginate:         1
baseurl:          /
author:
  name:           
  url:            
  email:          pandaba@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/honestcoyote
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'